<?php
namespace  app\common;

use Qiniu\Auth;
use Qiniu\Storage\UploadManager;
use think\Controller;

class  Base extends Controller {
     const  OK = 2001;                  //成功
     const  FAIL = 2000;                //失败
     const PARAMETER_ERROR= 2002;       //参数缺失
     const NOT_LOGGED_IN= 2003;         //未登入

     const JUMP_PAGE= 2100;             //跳转页面
     const POPUP= 2200;                 //弹窗
     const JURISDICTION_ERROR= 2300;    //权限错误
     const NOT_FIND= 2400;              //查找无结果

    static protected $page = 1;         //当前页码
    static protected $pageSize =  5;    //当前条数

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setPage();
    }
//获取分页信息
    public function setPage(){
        self::$page = $this->request->post('page',1);                   //当前的分页
        self::$pageSize = $this->request->post('page_size',5);  //当前分页数据条数
    }
   
}